cnn:
  image_size: 48
  channels: 3
  num_classes: 4
  learning_rate: 0.001
  batch_size: 64
  num_epochs: 25
efficientnet:
  image_size: 224
  channels: 3
  num_classes: 4
  learning_rate: 0.001
  batch_size: 128
  num_epochs: 25